// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQeepI1e4rsgx2iZ9KhY9-sJ8SxkFw2M',
    appId: '1:425615477157:web:3edfe40c000d1ee3c7404c',
    messagingSenderId: '425615477157',
    projectId: 'recomart0028',
    authDomain: 'recomart0028.firebaseapp.com',
    storageBucket: 'recomart0028.firebasestorage.app',
    measurementId: 'G-3FQKG7EL51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5TDfxQtOZQME_0kHuFTI4vidvsTOsrA',
    appId: '1:425615477157:android:c7780afb9694197bc7404c',
    messagingSenderId: '425615477157',
    projectId: 'recomart0028',
    storageBucket: 'recomart0028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWsu4IwzSYVjYCEzW7346W_c12OQ0wkM',
    appId: '1:425615477157:ios:a4ad748c684d7449c7404c',
    messagingSenderId: '425615477157',
    projectId: 'recomart0028',
    storageBucket: 'recomart0028.firebasestorage.app',
    iosBundleId: 'com.example.recomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcWsu4IwzSYVjYCEzW7346W_c12OQ0wkM',
    appId: '1:425615477157:ios:a4ad748c684d7449c7404c',
    messagingSenderId: '425615477157',
    projectId: 'recomart0028',
    storageBucket: 'recomart0028.firebasestorage.app',
    iosBundleId: 'com.example.recomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQeepI1e4rsgx2iZ9KhY9-sJ8SxkFw2M',
    appId: '1:425615477157:web:5b9a4fe9037838d7c7404c',
    messagingSenderId: '425615477157',
    projectId: 'recomart0028',
    authDomain: 'recomart0028.firebaseapp.com',
    storageBucket: 'recomart0028.firebasestorage.app',
    measurementId: 'G-YX2LY0P7XM',
  );
}
